import { Extension } from '@colony/colony-js';
import { BigNumber } from 'ethers';
import { toB32 } from '~utils';

export const COLONY_CURRENT_VERSION_KEY = 'colony';
export const NETWORK_INVERSE_FEE_DATABASE_ID = 'networkInverseFee';

export const SUPPORTED_EXTENSION_IDS = [
  Extension.OneTxPayment,
  Extension.VotingReputation,
  Extension.StakedExpenditure,
  Extension.StagedExpenditure,
  Extension.StreamingPayments,
  Extension.MultisigPermissions,
];

export const SIMPLE_DECISIONS_ACTION_CODE = '0x12345678';
export const BLOCK_PAGING_SIZE = process.env.BLOCK_PAGING_SIZE
  ? parseInt(process.env.BLOCK_PAGING_SIZE, 10)
  : 1000;

// These are indexes of data slots in contracts
// For more information: https://github.com/JoinColony/colonyNetwork/blob/develop/contracts/colony/ColonyStorage.sol
export const EXPENDITURES_SLOT = BigNumber.from(25);
export const EXPENDITURESLOTS_SLOT = BigNumber.from(26);

export const EXPENDITURE_OWNER_AND_STATUS = toB32(BigNumber.from(0));

export const EXPENDITURESLOT_RECIPIENT = toB32(BigNumber.from(0));
export const EXPENDITURESLOT_CLAIMDELAY = toB32(BigNumber.from(1));
export const EXPENDITURESLOT_PAYOUTMODIFIER = toB32(BigNumber.from(2));

// Make sure this is kept up to date with the same set in the CDapp
// src/routes/routeConstants.ts
export const RESERVED_ROUTES = new Set([
  '404',
  'meta',
  'account',
  'accounts',
  'activity',
  'activityfeed',
  'about',
  'admin',
  'adminpanel',
  'advanced',
  'affiliate',
  'analytics',
  'api',
  'app',
  'beta',
  'billing',
  'blog',
  'careers',
  'cdapp',
  'cdn',
  'changelog',
  'chat',
  'clny',
  'colony',
  'colonystaff',
  'colonyteam',
  'community',
  'company',
  'complaints',
  'conditions',
  'config',
  'contract',
  'contribute',
  'contributes',
  'create',
  'dao',
  'daoclub',
  'dapp',
  'dashboard',
  'data',
  'delete',
  'dev',
  'developer',
  'docs',
  'documentation',
  'edit',
  'email',
  'embed',
  'enterprise',
  'faq',
  'faqs',
  'features',
  'feedback',
  'file',
  'finance',
  'finances',
  'forum',
  'gateway',
  'general',
  'global',
  'help',
  'helpcenter',
  'home',
  'info',
  'integrations',
  'invalid',
  'invest',
  'jobs',
  'landing',
  'law',
  'legal',
  'legalnotice',
  'login',
  'logout',
  'management',
  'marketplace',
  'media',
  'meta',
  'metacolony',
  'metrics',
  'news',
  'notifications',
  'onboarding',
  'partner',
  'payment',
  'payments',
  'press',
  'pricing',
  'privacy',
  'privacypolicy',
  'private',
  'process',
  'product',
  'profile',
  'profileuser',
  'project',
  'projects',
  'promo',
  'promotion',
  'public',
  'query',
  'register',
  'report',
  'roadmap',
  'root',
  'sales',
  'search',
  'security',
  'services',
  'settings',
  'shop',
  'sitemap',
  'staff',
  'status',
  'streaming',
  'support',
  'team',
  'terms',
  'test',
  'tests',
  'tools',
  'tracking',
  'transaction',
  'transactions',
  'translate',
  'updates',
  'upload',
  'user',
  'userpanel',
  'verified',
  'webhooks',
  'welcome',
  'whitepaper',
  'work',
]);
